"""create users table

Revision ID: 771fd5382fc7
Revises:
Create Date: 2025-10-29 11:04:11.287812

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = '771fd5382fc7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
